// This section will give the Json Values to the rest of the application

var ResistorValues = {
                        "Value": "10", "ColorDigitOne": 'brown', "ColorDigitTwo": 'black', "Multiplier": 'black', 
                        "Value": "15", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "22", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "33", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "47", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "68", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "100", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": ,
                        "Value": "120", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": ,
                        "Value": "150", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "180", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "220", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "270", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , 
                        "Value": "330", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "390", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "470", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "560", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "680", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.0k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.2k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.5k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.8k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "2.2k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "2.7k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "3.3k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "3.9k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "4.7k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "5.6k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "6.8k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "10k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "12k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "15k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "18k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "22k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "27k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "33k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "39k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "47k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "56k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "68k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "100k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "120k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "150k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "180k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "220k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "270k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "330k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "390k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "470k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "560k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "680k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.0M", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.5M", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "2.2M", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "3.3M", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "4.7M", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "6.8M", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": 
                     };

var CapacitorValues = {
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                      };

var InductorValues = {
                        "Value": , "ColorDigitOne": , "ColorDigitTwo:" , "Multiplier": , "Tolerance": ,
                     };