// This section will give the Json Values to the rest of the application

var ResistorValues = {
                        "Value": "10", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "15", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "22", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "33", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "47", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "68", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "100", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "120", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "150", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "180", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "220", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "270", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "330", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "390", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "470", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "560", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "680", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.0k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.2k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.5k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "1.8k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "2.2k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": "2.7k", "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                        
                     };

var CapacitorValues = {
                        "Value": , "ColorDigitOne": , "ColorDigitTwo": , "Multiplier": , "Tolerance": ,
                      };

var InductorValues = {
                        "Value": , "ColorDigitOne": , "ColorDigitTwo:" , "Multiplier": , "Tolerance": ,
                     };